export const seedData = [
  {
    image: 'https://xsgames.co/randomusers/assets/avatars/male/10.jpg',
    name: 'Cally Hahn',
    salary: 200000,
    status: 'active',
    role: 'software engineer',
    typeEmployee: 'full time',
  },
  {
    image: 'https://xsgames.co/randomusers/assets/avatars/male/37.jpg',
    name: 'Dimitri Wainwright',
    salary: 300000,
    status: 'active',
    role: 'executive assistants',
    typeEmployee: 'full time',
  },
  {
    image: 'https://xsgames.co/randomusers/assets/avatars/male/64.jpg',
    name: 'Tyreese Mercer',
    salary: 400000,
    status: 'active',
    role: 'software engineer',
    typeEmployee: 'full time',
  },
  {
    image: 'https://xsgames.co/randomusers/assets/avatars/male/44.jpg',
    name: 'Debra Pearson',
    salary: 100000,
    status: 'active',
    role: 'accountant',
    typeEmployee: 'full time',
  },
  {
    image: 'https://xsgames.co/randomusers/assets/avatars/male/66.jpg',
    name: 'Milton Clarkson',
    salary: 250000,
    status: 'active',
    role: 'product manager',
    typeEmployee: 'full time',
  },
  {
    image: 'https://xsgames.co/randomusers/assets/avatars/male/40.jpg',
    name: 'Shakeel John',
    salary: 150000,
    status: 'active',
    role: 'business analyst',
    typeEmployee: 'full time',
  },
  {
    image: 'https://xsgames.co/randomusers/assets/avatars/female/35.jpg',
    name: 'Aiysha Curran',
    salary: 270000,
    status: 'active',
    role: 'sales representative',
    typeEmployee: 'full time',
  },
  {
    image: 'https://xsgames.co/randomusers/assets/avatars/female/10.jpg',
    name: 'Leela Kearns',
    salary: 70000,
    status: 'active',
    role: 'Administrative assistant',
    typeEmployee: 'full time',
  },
  {
    image: 'https://xsgames.co/randomusers/assets/avatars/female/22.jpg',
    name: 'Esmae Sweet',
    salary: 120000,
    status: 'active',
    role: 'Marketing specialist',
    typeEmployee: 'full time',
  },
  {
    image: 'https://xsgames.co/randomusers/assets/avatars/female/17.jpg',
    name: 'Agata Mccullough',
    salary: 330000,
    status: 'active',
    role: 'software engineer',
    typeEmployee: 'full time',
  },
  {
    image: 'https://xsgames.co/randomusers/assets/avatars/female/0.jpg',
    name: 'Project manager',
    salary: 380000,
    status: 'active',
    role: 'software engineer',
    typeEmployee: 'full time',
  },
];
